### ISSUE TITLE
Lav "ren" hjemmeside til mobilen

### ISSUE THREAD

**Issue by Carditis** [LFalch/gentfight#10]

**Comment by LFalch** [comment]
😕

**Comment by LFalch** [comment]
@Carditis Hvad betyder det her?

**Comment by Carditis** [comment]
Vi skal bare have en hjemmeside, som ikke rigtig kan gøre noget. Den skal senere laves både pænere og mere brugbar. Den skal ikke på denne fase ikke indeholde nogle migmig'er

**Comment by LFalch** [comment]
Er det ikke blevet gjort?
