### ISSUE TITLE
Kebablogistik

### ISSUE THREAD

**Issue by LordLaxatives** [LFalch/gentfight#23]
Der skal sikres en konsistent og pålidelig måde at anskaffe samt levere kebab, uden at folk risikerer at dø på vejen.

**Comment by LFalch** [comment]
Hvor tit kører busser?

**Comment by LordLaxatives** [comment]
Ikke ofte nok. Det eneste, der fungerer, er at anskaffe sig et fartøj selv. Plus, alle buschauffører i Holbæk området har en historik med narkotika, dermed er det umuligt at undgå at dø på vejen til kebabben.

**Comment by Carditis** [comment]
Kan vi få kommunalstøtte til vores kebabforbrug?🤷‍♂️
