### ISSUE TITLE
Draw characters that animate

### ISSUE THREAD

**Issue by Carditis** [LFalch/gentfight#4]
- [x] Idle Animation.
- [x] Punch animation.
- [x] Block animation.
- [x] Animation when taking damage.
- [x] Animation when loosing.
- [x] Animation for being stunned after punching and opponent blocks

**Comment by LFalch** [comment]
We need something that resembles the fighters. Initially probably some boxes with some extra boxes as arms and maybe legs. The arms will animate to resemble a move. The moves will initially be punch and block.

**Comment by LFalch** [comment]
Later we'll want some drawing probably by @deadlap.
